### ISSUE TITLE
Awesome tool

### ISSUE THREAD

**Issue by carlblanchard** [barry-jones/live-documenter#43]
Barry, Firstly thank you. I stumbled across your tool this morning and I must say "It's frigging awesome"
I have used other documentation tools in the past and well in just a few hours, I've set up your exporter on my DevOps build pipeline and have the documents published to an intranet site. (Very impressive). However, I have some questions.

- Your SSL looks like it may have expired, you might want to check that out.

- Sadly when I point to my .sln file in the configuration It fails to pick up anything. 
I added my output.dll in the configuration/document tag which generates the documentation so as a workaround can you have multiple documents? 
- How can I get the output to overwrite the existing files?

**Comment by barry-jones** [comment]
Hi Carl, thanks for your kind words. I am glad you are finding it helpful!

Thanks for the heads up on these issues, I think that the solution reading issues will be to do with the latest file formats. Are you using VS 2019? Is there anything distinct or interesting about the makeup of the solution and project files?

With regards to overwriting, this option is no longer available in the application. I can see how this would be useful in your circumstances, and for other people - so it will probably be added back in at some point.

**Comment by carlblanchard** [comment]
Hi Barry, Apologies for a really late reply. Yeah, I am using VS2019. 

Another good feature would be, amalgamating multiple .csproj or .sln files into a single output. 
I am not sure if it already caters for this but as most projects these days are spread across multiple projects and solutions I think this is a must.

**Comment by barry-jones** [comment]
Hi, there is a concept of a project file which allows you to manage multiple libraries, solutions or indeed exclude libraries from a solution. [http://livedocumenter.barryjones.me.uk/docs/application/desktop/ldproj-files/](http://livedocumenter.barryjones.me.uk/docs/application/desktop/ldproj-files/)

```
<?xml version="1.0"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <files>
    <file>E:/projects/csv-validator/FormatValidator.sln</file>
    <file>E:/projects/live-documenter/developersuite.sln</file>
  </files>
  <RemovedAssemblies />
  <filters>
    <filter>Public</filter>
    <filter>Protected</filter>
  </filters>
  <language>CSharp</language>
</project>
```

These can be created from the UI or managed as XML files. You can pass these as in the exporter cli directly or via configuration files as required. They do need to have an `ldproj` extension.

`.\exporter.exe "C:\testing.ldproj" -to "C:\docs"`

**Comment by carlblanchard** [comment]
Thanks, Barry. Can this be done from the command line? I have document and LDEC currently in my XML config file. 
Below is an example of what I have and what I would like. The commented out code is what I currently have, and the files are what you suggested, which I would like. 
``` XML
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <!-- <document>PathToProjectOutput.dll</document>-->
  <files>
    <file>C:\ProjectA.csproj</file>
    <file>C:\ProjectB.csproj</file>
  </files>	
	<filters>
		<filter>Public</filter>
		<filter>Protected</filter>
    <filter>Internal</filter>
    <filter>InternalProtected</filter>
    <filter>Private</filter>
	</filters>
  <outputs>
	  <ldec location="C:\APIDocusWebsite\">web-msdn.ldec</ldec>
  </outputs>
</configuration>

```
When running through pipeline I get the following. 
![image](https://user-images.githubusercontent.com/18427214/104654268-b6be6d80-56b3-11eb-896f-b8cf72fd63a8.png)

**Comment by barry-jones** [comment]
Hi. Yes it does support it. Maybe this is something I could simplify in the future but here is the gist.

**Briefly: you need to specify the `ldproj` file in the `configuration`s `document` property.**

The `ldproj` file is really a replacement for an sln, or csproj file. In that it manages what a project is for the documentation. Which libraries are output and which are ignored.

The configuration is what tells the exporter what to do. What input to use and what output files to produce. There is a confusing overlap here with the filters (those are for the UI). Hopefully that gives you a better understanding.

For example, if the below `ldproj` file is `c:\scratch\test.ldproj`:

```
<?xml version="1.0"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <files>
    <file>E:/projects/csv-validator/FormatValidator.sln</file>
    <file>E:/projects/live-documenter/developersuite.sln</file>
  </files>
  <RemovedAssemblies />
  <filters>
    <filter>Public</filter>
    <filter>Protected</filter>
  </filters>
  <language>CSharp</language>
</project>
```

The configuration file would be:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <document>c:\scratch\test.ldproj</document>
	
	<!-- can be Public|Internal|Protected|ProtectedInternal|Private only those detailed will be output,
		not specifiying a filter section will result in only the Public members being exported.
    
    If these are specified and the document is an ldproj file then these will override the 
    ldproj files filters. In the event that the document is not an ldprof file these will 
    need to specified.
	-->	
	<filters>
		<filter>Public</filter>
		<filter>Protected</filter>
    <filter>Internal</filter>
    <filter>InternalProtected</filter>
    <filter>Private</filter>
	</filters>
  	
	<!-- the application will always check the ApplicationData folder for LDEC files -->
  <outputs>
	<!-- the locations being output to will have new folders created inside them -->
    <ldec location="c:\temp\web\">web-msdn.ldec</ldec>
    <ldec location="c:\temp\web-refresh\">web-refresh.ldec</ldec>
    <ldec location="c:\temp\htmlhelp-1\">htmlhelp1-msdn.ldec</ldec>
    <ldec location="c:\temp\htmlhelp-2\">htmlhelp2-msdn.ldec</ldec>
    <ldec location="c:\temp\helpviewer-1\">helpviewer1-msdn.ldec</ldec>
    <ldec location="c:\temp\xml\">xml.ldec</ldec>
  </outputs>
</configuration>
```

**Comment by carlblanchard** [comment]
Ahh!!!! Simples when you know-how. That's awesome.
I still can't get it to output populated information when just using .sln files, I have to compile into .dll's first then point at them.
Any ideas?  Also, Barry, does this support features like <example><code> etc.
https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/language-specification/documentation-comments

**Comment by barry-jones** [comment]
I will look in to the solution files issue but in the mean time, here is a list of the supported comments: https://livedocumenter.barryjones.me.uk/docs/supported-xml-comments/

**Comment by barry-jones** [comment]
Hi, I am struggling to replicate the SLN. If you could provide some more detail that could be helpful.

How many projects and what type are included. What language are the projects in, which Framework or Core version are they running.

If you could also provide some of the details, or if possible attach a .*proj file of one of the projects that are not showing up in the documentation, that would also be useful.

**Comment by carlblanchard** [comment]
No, I take that back. It's working, let's put it down to PEBKAC. I must have been doing something wrong. 
I think the only difference is. I now build the solution, whereas before I was just downloading in the pipeline and building the documentation from the .sln which hadn't been built. 
Barry, thanks for writing this awesome documenting tool. Thanks for the great assistance. Do you have an email I can reach you on? I have some ideas for you on this.
